# 001 - Data Exploration

Goal: load the local BIRD mini-dev Arrow dataset and inspect the first few examples.

This dataset is not bird images. **BIRD** here is a text-to-SQL benchmark dataset. Each row contains a natural-language question, optional evidence, the target SQL query, and a difficulty label.

In [1]:
pip install pandas

Requirement already satisfied: pandas in d:\Code\Finetuning a model\.venv312\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in d:\Code\Finetuning a model\.venv312\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\Code\Finetuning a model\.venv312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Code\Finetuning a model\.venv312\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in d:\Code\Finetuning a model\.venv312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from pathlib import Path

import pandas as pd
from datasets import Dataset

pd.set_option("display.max_colwidth", 140)

d:\Code\Finetuning a model\.venv312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
PROJECT_ROOT = Path.cwd()

# When this notebook is opened from the notebooks folder, move up to the project root.
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATASET_PATH = PROJECT_ROOT / "data" / "bird_mini_dev" / "raw" / "bird-original.arrow"

print(f"Project root: {PROJECT_ROOT}")
print(f"Dataset path: {DATASET_PATH}")
print(f"Dataset exists: {DATASET_PATH.exists()}")

Project root: d:\Code\Finetuning a model
Dataset path: d:\Code\Finetuning a model\data\bird_mini_dev\raw\bird-original.arrow
Dataset exists: True

In [4]:
ds = Dataset.from_file(str(DATASET_PATH))

print(ds)
print("Columns:", ds.column_names)

Dataset({
    features: ['question_id', 'db_id', 'question', 'evidence', 'SQL', 'difficulty'],
    num_rows: 500
})
Columns: ['question_id', 'db_id', 'question', 'evidence', 'SQL', 'difficulty']

In [5]:
first_10 = ds.select(range(10)).to_pandas()
first_10

,question_id,db_id,question,evidence,SQL,difficulty
0,1471,debit_card_specializing,What is the ratio of customers who pay in EUR against customers who pay in CZK?,ratio of customers who pay in EUR against customers who pay in CZK = count(Currency = 'EUR') / count(Currency = 'CZK').,"SELECT CAST(SUM(IIF(Currency = 'EUR', 1, 0)) AS FLOAT) / SUM(IIF(Currency = 'CZK', 1, 0)) AS ratio FROM customers",simple
1,1472,debit_card_specializing,"In 2012, who had the least consumption in LAM?",Year 2012 can be presented as Between 201201 And 201212; The first 4 strings of the Date values in the yearmonth table can represent year.,SELECT T1.CustomerID FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE T1.Segment = 'LAM' AND SUBST...,moderate
2,1473,debit_card_specializing,What was the average monthly consumption of customers in SME for the year 2013?,Average Monthly consumption = AVG(Consumption) / 12; Year 2013 can be presented as Between 201301 And 201312; The first 4 strings of the...,"SELECT AVG(T2.Consumption) / 12 FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE SUBSTR(T2.Date, 1...",moderate
3,1476,debit_card_specializing,What was the difference in gas consumption between CZK-paying customers and EUR-paying customers in 2012?,Year 2012 can be presented as Between 201201 And 201212; The first 4 strings of the Date values in the yearmonth table can represent yea...,"SELECT SUM(IIF(T1.Currency = 'CZK', T2.Consumption, 0)) - SUM(IIF(T1.Currency = 'EUR', T2.Consumption, 0)) FROM customers AS T1 INNER JO...",challenging
4,1479,debit_card_specializing,Which year recorded the most consumption of gas paid in CZK?,The first 4 strings of the Date values in the yearmonth table can represent year.,"SELECT SUBSTR(T2.Date, 1, 4) FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE T1.Currency = 'CZK' ...",moderate
5,1480,debit_card_specializing,What was the gas consumption peak month for SME customers in 2013?,Year 2013 can be presented as Between 201301 And 201312; The first 4 strings of the Date values in the yearmonth table can represent yea...,"SELECT SUBSTR(T2.Date, 5, 2) FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE SUBSTR(T2.Date, 1, 4...",moderate
6,1481,debit_card_specializing,What is the difference in the annual average consumption of the customers with the least amount of consumption paid in CZK for 2013 betw...,annual average consumption of customer with the lowest consumption in each segment = total consumption per year / the number of customer...,"SELECT CAST(SUM(IIF(T1.Segment = 'SME', T2.Consumption, 0)) AS REAL) / COUNT(T1.CustomerID) - CAST(SUM(IIF(T1.Segment = 'LAM', T2.Consum...",challenging
7,1482,debit_card_specializing,"Which of the three segments—SME, LAM and KAM—has the biggest and lowest percentage increases in consumption paid in EUR between 2012 and...",Increase or Decrease = consumption for 2013 - consumption for 2012; Percentage of Increase = (Increase or Decrease / consumption for 201...,"SELECT CAST((SUM(IIF(T1.Segment = 'SME' AND T2.Date LIKE '2013%', T2.Consumption, 0)) - SUM(IIF(T1.Segment = 'SME' AND T2.Date LIKE '201...",challenging
8,1483,debit_card_specializing,How much did customer 6 consume in total between August and November 2013?,Between August And November 2013 refers to Between 201308 And 201311; The first 4 strings of the Date values in the yearmonth table can ...,SELECT SUM(Consumption) FROM yearmonth WHERE CustomerID = 6 AND Date BETWEEN '201308' AND '201311',simple
9,1484,debit_card_specializing,"How many more ""discount"" gas stations does the Czech Republic have compared to Slovakia?",Czech Republic can be represented as the Country value in gasstations table is 'CZE'; Slovakia can be represented as the Country value i...,"SELECT SUM(IIF(Country = 'CZE', 1, 0)) - SUM(IIF(Country = 'SVK', 1, 0)) FROM gasstations WHERE Segment = 'Discount'",simple

In [6]:
first_10[["question_id", "difficulty", "question", "SQL"]]

,question_id,difficulty,question,SQL
0,1471,simple,What is the ratio of customers who pay in EUR against customers who pay in CZK?,"SELECT CAST(SUM(IIF(Currency = 'EUR', 1, 0)) AS FLOAT) / SUM(IIF(Currency = 'CZK', 1, 0)) AS ratio FROM customers"
1,1472,moderate,"In 2012, who had the least consumption in LAM?",SELECT T1.CustomerID FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE T1.Segment = 'LAM' AND SUBST...
2,1473,moderate,What was the average monthly consumption of customers in SME for the year 2013?,"SELECT AVG(T2.Consumption) / 12 FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE SUBSTR(T2.Date, 1..."
3,1476,challenging,What was the difference in gas consumption between CZK-paying customers and EUR-paying customers in 2012?,"SELECT SUM(IIF(T1.Currency = 'CZK', T2.Consumption, 0)) - SUM(IIF(T1.Currency = 'EUR', T2.Consumption, 0)) FROM customers AS T1 INNER JO..."
4,1479,moderate,Which year recorded the most consumption of gas paid in CZK?,"SELECT SUBSTR(T2.Date, 1, 4) FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE T1.Currency = 'CZK' ..."
5,1480,moderate,What was the gas consumption peak month for SME customers in 2013?,"SELECT SUBSTR(T2.Date, 5, 2) FROM customers AS T1 INNER JOIN yearmonth AS T2 ON T1.CustomerID = T2.CustomerID WHERE SUBSTR(T2.Date, 1, 4..."
6,1481,challenging,What is the difference in the annual average consumption of the customers with the least amount of consumption paid in CZK for 2013 betw...,"SELECT CAST(SUM(IIF(T1.Segment = 'SME', T2.Consumption, 0)) AS REAL) / COUNT(T1.CustomerID) - CAST(SUM(IIF(T1.Segment = 'LAM', T2.Consum..."
7,1482,challenging,"Which of the three segments—SME, LAM and KAM—has the biggest and lowest percentage increases in consumption paid in EUR between 2012 and...","SELECT CAST((SUM(IIF(T1.Segment = 'SME' AND T2.Date LIKE '2013%', T2.Consumption, 0)) - SUM(IIF(T1.Segment = 'SME' AND T2.Date LIKE '201..."
8,1483,simple,How much did customer 6 consume in total between August and November 2013?,SELECT SUM(Consumption) FROM yearmonth WHERE CustomerID = 6 AND Date BETWEEN '201308' AND '201311'
9,1484,simple,"How many more ""discount"" gas stations does the Czech Republic have compared to Slovakia?","SELECT SUM(IIF(Country = 'CZE', 1, 0)) - SUM(IIF(Country = 'SVK', 1, 0)) FROM gasstations WHERE Segment = 'Discount'"

A useful first habit: always inspect the label/target column. In this dataset, the thing a model would learn to generate is the `SQL` column.